// Generated by tools/build_lootbox_data.py from the Crawler Sheets catalog. Do not edit.
var LOOT_DATA = {
 "stats": [
  "Strength",
  "Intelligence",
  "Constitution",
  "Dexterity",
  "Charisma"
 ],
 "skills": [
  {
   "name": "Back Claw",
   "group": "Animal Crawler & Pet Strike Skills"
  },
  {
   "name": "Bite",
   "group": "Animal Crawler & Pet Strike Skills"
  },
  {
   "name": "Slice Attack",
   "group": "Animal Crawler & Pet Strike Skills"
  },
  {
   "name": "Club",
   "group": "Bashing Weapon Skills"
  },
  {
   "name": "Improvised Weapons",
   "group": "Bashing Weapon Skills"
  },
  {
   "name": "Warhammer",
   "group": "Bashing Weapon Skills"
  },
  {
   "name": "Axe",
   "group": "Edged Weapon Skills"
  },
  {
   "name": "Dagger",
   "group": "Edged Weapon Skills"
  },
  {
   "name": "Longsword",
   "group": "Edged Weapon Skills"
  },
  {
   "name": "Rapier",
   "group": "Edged Weapon Skills"
  },
  {
   "name": "Foot Soldier",
   "group": "Hand-to-hand Combat Skills"
  },
  {
   "name": "Noggin Nocker",
   "group": "Hand-to-hand Combat Skills"
  },
  {
   "name": "Pugilism",
   "group": "Hand-to-hand Combat Skills"
  },
  {
   "name": "Unarmed Combat",
   "group": "Hand-to-hand Combat Skills"
  },
  {
   "name": "Wrasslin’",
   "group": "Hand-to-hand Combat Skills"
  },
  {
   "name": "Choke Out",
   "group": "Hand-to-hand Damage Effect Skills"
  },
  {
   "name": "Dirty Fighting",
   "group": "Hand-to-hand Damage Effect Skills"
  },
  {
   "name": "Iron Punch",
   "group": "Hand-to-hand Damage Effect Skills"
  },
  {
   "name": "Powerful Strike",
   "group": "Hand-to-hand Damage Effect Skills"
  },
  {
   "name": "Skullcracker",
   "group": "Hand-to-hand Damage Effect Skills"
  },
  {
   "name": "Smush",
   "group": "Hand-to-hand Damage Effect Skills"
  },
  {
   "name": "Toss",
   "group": "Hand-to-hand Damage Effect Skills"
  },
  {
   "name": "Creepy Chains",
   "group": "Racial (Changbi Demon)"
  },
  {
   "name": "Bow",
   "group": "Ranged Weapon Skills"
  },
  {
   "name": "Crossbow",
   "group": "Ranged Weapon Skills"
  },
  {
   "name": "Handgun",
   "group": "Ranged Weapon Skills"
  },
  {
   "name": "Javelin",
   "group": "Ranged Weapon Skills"
  },
  {
   "name": "Shotgun",
   "group": "Ranged Weapon Skills"
  },
  {
   "name": "Shuriken",
   "group": "Ranged Weapon Skills"
  },
  {
   "name": "Slingshot",
   "group": "Ranged Weapon Skills"
  },
  {
   "name": "Herding Weapons",
   "group": "Reach Weapon Skills"
  },
  {
   "name": "Lance",
   "group": "Reach Weapon Skills"
  },
  {
   "name": "Polearm",
   "group": "Reach Weapon Skills"
  },
  {
   "name": "Quarterstaff",
   "group": "Reach Weapon Skills"
  },
  {
   "name": "Acute Ears",
   "group": "Utility Skills"
  },
  {
   "name": "Aiming",
   "group": "Utility Skills"
  },
  {
   "name": "Alchemy",
   "group": "Utility Skills"
  },
  {
   "name": "Ambush",
   "group": "Utility Skills"
  },
  {
   "name": "Animal Handling",
   "group": "Utility Skills"
  },
  {
   "name": "Arcane",
   "group": "Utility Skills"
  },
  {
   "name": "Attack of Opportunity",
   "group": "Utility Skills"
  },
  {
   "name": "Backfire",
   "group": "Utility Skills"
  },
  {
   "name": "Balance",
   "group": "Utility Skills"
  },
  {
   "name": "Basic Science",
   "group": "Utility Skills"
  },
  {
   "name": "Bomb Surgeon",
   "group": "Utility Skills"
  },
  {
   "name": "Calligraphy",
   "group": "Utility Skills"
  },
  {
   "name": "Cartography",
   "group": "Utility Skills"
  },
  {
   "name": "Cat-like Reflexes",
   "group": "Utility Skills"
  },
  {
   "name": "Catcher",
   "group": "Utility Skills"
  },
  {
   "name": "Cesta Punta",
   "group": "Utility Skills"
  },
  {
   "name": "Character Actor",
   "group": "Utility Skills"
  },
  {
   "name": "Chopper Pilot",
   "group": "Utility Skills"
  },
  {
   "name": "Climbing",
   "group": "Utility Skills"
  },
  {
   "name": "Cockroach",
   "group": "Utility Skills"
  },
  {
   "name": "Cooking",
   "group": "Utility Skills"
  },
  {
   "name": "Deception",
   "group": "Utility Skills"
  },
  {
   "name": "Detect Lies",
   "group": "Utility Skills"
  },
  {
   "name": "Detect Trap",
   "group": "Utility Skills"
  },
  {
   "name": "Determine Value",
   "group": "Utility Skills"
  },
  {
   "name": "Diplomacy",
   "group": "Utility Skills"
  },
  {
   "name": "Dodge",
   "group": "Utility Skills"
  },
  {
   "name": "Double Tap",
   "group": "Utility Skills"
  },
  {
   "name": "Driving",
   "group": "Utility Skills"
  },
  {
   "name": "Dumpster Diving",
   "group": "Utility Skills"
  },
  {
   "name": "Endurance",
   "group": "Utility Skills"
  },
  {
   "name": "Engineering",
   "group": "Utility Skills"
  },
  {
   "name": "Escape Artist",
   "group": "Utility Skills"
  },
  {
   "name": "Escape Plan",
   "group": "Utility Skills"
  },
  {
   "name": "Explosives Handling",
   "group": "Utility Skills"
  },
  {
   "name": "Fabricate",
   "group": "Utility Skills"
  },
  {
   "name": "Find Crawler",
   "group": "Utility Skills"
  },
  {
   "name": "Find Trap",
   "group": "Utility Skills"
  },
  {
   "name": "First Aid",
   "group": "Utility Skills"
  },
  {
   "name": "Gear Head",
   "group": "Utility Skills"
  },
  {
   "name": "Goblin Explosives",
   "group": "Utility Skills"
  },
  {
   "name": "Good First Impression",
   "group": "Utility Skills"
  },
  {
   "name": "Hide in Shadows",
   "group": "Utility Skills"
  },
  {
   "name": "Improvised Explosive Device",
   "group": "Utility Skills"
  },
  {
   "name": "Incendiary Device Handling",
   "group": "Utility Skills"
  },
  {
   "name": "Infusion",
   "group": "Utility Skills"
  },
  {
   "name": "Intimidate",
   "group": "Utility Skills"
  },
  {
   "name": "Investigation",
   "group": "Utility Skills"
  },
  {
   "name": "Iron Stomach",
   "group": "Utility Skills"
  },
  {
   "name": "Jumping",
   "group": "Utility Skills"
  },
  {
   "name": "Leadership",
   "group": "Utility Skills"
  },
  {
   "name": "Light on Your Feet",
   "group": "Utility Skills"
  },
  {
   "name": "Lockpicking",
   "group": "Utility Skills"
  },
  {
   "name": "Lore",
   "group": "Utility Skills"
  },
  {
   "name": "Negotiation",
   "group": "Utility Skills"
  },
  {
   "name": "Pathfinder",
   "group": "Utility Skills"
  },
  {
   "name": "Perception",
   "group": "Utility Skills"
  },
  {
   "name": "Performance",
   "group": "Utility Skills"
  },
  {
   "name": "Persuasion",
   "group": "Utility Skills"
  },
  {
   "name": "Regeneration",
   "group": "Utility Skills"
  },
  {
   "name": "Religion",
   "group": "Utility Skills"
  },
  {
   "name": "Repair",
   "group": "Utility Skills"
  },
  {
   "name": "Riding",
   "group": "Utility Skills"
  },
  {
   "name": "Ropework",
   "group": "Utility Skills"
  },
  {
   "name": "Running",
   "group": "Utility Skills"
  },
  {
   "name": "Salvage",
   "group": "Utility Skills"
  },
  {
   "name": "Scutelliphily",
   "group": "Utility Skills"
  },
  {
   "name": "Shield Block",
   "group": "Utility Skills"
  },
  {
   "name": "Sleight of Hand",
   "group": "Utility Skills"
  },
  {
   "name": "Smithing",
   "group": "Utility Skills"
  },
  {
   "name": "Stealth",
   "group": "Utility Skills"
  },
  {
   "name": "Streetwise",
   "group": "Utility Skills"
  },
  {
   "name": "Survival",
   "group": "Utility Skills"
  },
  {
   "name": "Swimming",
   "group": "Utility Skills"
  },
  {
   "name": "Tactics",
   "group": "Utility Skills"
  },
  {
   "name": "Tattoo Artistry",
   "group": "Utility Skills"
  },
  {
   "name": "Taunt",
   "group": "Utility Skills"
  },
  {
   "name": "Throwing",
   "group": "Utility Skills"
  },
  {
   "name": "Tracking",
   "group": "Utility Skills"
  },
  {
   "name": "Trap Engineer",
   "group": "Utility Skills"
  },
  {
   "name": "Zone of Control",
   "group": "Utility Skills"
  }
 ],
 "spells": [
  {
   "name": "Air Buddy",
   "mana": "12"
  },
  {
   "name": "Astral Paw (Astral Hand, Astral Claw)",
   "mana": "12"
  },
  {
   "name": "Bad Faith",
   "mana": "10"
  },
  {
   "name": "Bang Bro",
   "mana": "5"
  },
  {
   "name": "Clockwork Triplicate",
   "mana": "26"
  },
  {
   "name": "Confusing Fog",
   "mana": "6"
  },
  {
   "name": "Dirt Clod",
   "mana": "1"
  },
  {
   "name": "Drain Life",
   "mana": "14"
  },
  {
   "name": "Earworm",
   "mana": "6"
  },
  {
   "name": "Fear",
   "mana": "3"
  },
  {
   "name": "Fire Fingers",
   "mana": "3"
  },
  {
   "name": "Fireball",
   "mana": "45"
  },
  {
   "name": "Frost Scar",
   "mana": "2"
  },
  {
   "name": "Grand Illusion",
   "mana": "7"
  },
  {
   "name": "Heal",
   "mana": "2"
  },
  {
   "name": "Heal Critter",
   "mana": "8"
  },
  {
   "name": "Heal Others",
   "mana": "6"
  },
  {
   "name": "Heal Self",
   "mana": "1"
  },
  {
   "name": "Hole",
   "mana": "12"
  },
  {
   "name": "Holy Aura",
   "mana": "7"
  },
  {
   "name": "Hot Stuff Aura",
   "mana": "8"
  },
  {
   "name": "Ice Blast",
   "mana": "9"
  },
  {
   "name": "Icicles",
   "mana": "19"
  },
  {
   "name": "Intimate Touches",
   "mana": "8"
  },
  {
   "name": "Lightning Bolt",
   "mana": "15"
  },
  {
   "name": "Magic Missile",
   "mana": "5"
  },
  {
   "name": "Mind Tickle",
   "mana": "2"
  },
  {
   "name": "Minion Army",
   "mana": "50"
  },
  {
   "name": "Nature’s Breath",
   "mana": "6"
  },
  {
   "name": "Oakhide",
   "mana": "5"
  },
  {
   "name": "Paladin’s Smite",
   "mana": "11"
  },
  {
   "name": "Panty Dropper",
   "mana": "10"
  },
  {
   "name": "Ping",
   "mana": "5"
  },
  {
   "name": "Protective Shell",
   "mana": "None"
  },
  {
   "name": "Puddle Jumper",
   "mana": "20"
  },
  {
   "name": "Rise, Dead Minion!",
   "mana": "10"
  },
  {
   "name": "Rootfoot",
   "mana": "5"
  },
  {
   "name": "Second Chance",
   "mana": "10"
  },
  {
   "name": "Shield",
   "mana": "8"
  },
  {
   "name": "Shock Treatment",
   "mana": "2"
  },
  {
   "name": "Solsplash",
   "mana": "13"
  },
  {
   "name": "Soul Collector",
   "mana": "4"
  },
  {
   "name": "Thunderlash",
   "mana": "12"
  },
  {
   "name": "Torch",
   "mana": "1"
  },
  {
   "name": "Tripper",
   "mana": "None"
  },
  {
   "name": "Turn Undead",
   "mana": "9"
  },
  {
   "name": "Twinkle Toes",
   "mana": "2"
  },
  {
   "name": "Unnecessary Force",
   "mana": "13"
  },
  {
   "name": "Vine Porn",
   "mana": "3"
  },
  {
   "name": "Wall of Fire",
   "mana": "15"
  },
  {
   "name": "Water Breathing",
   "mana": "2"
  },
  {
   "name": "Web",
   "mana": "6"
  },
  {
   "name": "Wilbur’s Slow-build Fireblast",
   "mana": "60"
  },
  {
   "name": "Wisp Armor",
   "mana": "5"
  }
 ],
 "damageTypes": [
  "Acid",
  "Bludgeoning",
  "Electric",
  "Fire",
  "Force",
  "Holy",
  "Ice",
  "Necrotic",
  "Piercing",
  "Poison",
  "Psychic",
  "Slashing",
  "Sonic"
 ],
 "gearSlots": [
  "Head",
  "Torso",
  "Arms",
  "Hands/Holding",
  "Legs",
  "Feet",
  "Belt",
  "Cape",
  "Accessories",
  "Weapon"
 ],
 "items": [
  "Healing Potion",
  "Good Healing Potion",
  "Gold Standard Healing Potion",
  "Standard Mana Potion",
  "Bandage",
  "Poison Antidote",
  "Torch",
  "Dynamite",
  "Good Goblin Dynamite",
  "Snack Bar"
 ],
 "tiers": [
  "Bronze",
  "Silver",
  "Gold",
  "Platinum",
  "Legendary",
  "Celestial"
 ],
 "categories": [
  "Adventurer",
  "Boss",
  "Fan",
  "Benefactor",
  "Mystery",
  "Quest",
  "Floor"
 ]
};
