"""Build gdocs-lootbox/Data.gs (and data.js for the local preview) from the app's catalog.

Exports names, groups and Mana costs only (no rulebook text).
Run: npm run lootbox
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'src'
OUT = ROOT / 'gdocs-lootbox'

KIND_GROUPS = {
    'attack': 'Other Attack Skills',
    'damageEffect': 'Other Damage Effect Skills',
    'utility': 'Utility Skills',
}


def ts_string_list(path: Path, const: str) -> list[str]:
    text = path.read_text()
    m = re.search(rf'export const {const}\b[^=]*=\s*\[(.*?)\]', text, re.S)
    if not m:
        raise SystemExit(f'{const} not found in {path}')
    return re.findall(r"'([^']*)'", m.group(1))


def main() -> None:
    skills = json.loads((SRC / 'data/skills.json').read_text())
    spells = json.loads((SRC / 'data/spells.json').read_text())

    types_ts = (SRC / 'engine/types.ts').read_text()
    slots = re.findall(r"\{ key: '(\w+)', label: '([^']+)'", types_ts.split('GEAR_SLOTS', 1)[1])

    extras = (SRC / 'data/extras.ts').read_text()
    items_block = extras.split('export const ITEMS', 1)[1].split(']\n', 1)[0]
    items = re.findall(r"name: '([^']+)'", items_block)

    data = {
        'stats': ['Strength', 'Intelligence', 'Constitution', 'Dexterity', 'Charisma'],
        'skills': sorted(
            ({'name': s['name'], 'group': s.get('group') or KIND_GROUPS.get(s['kind'], 'Other Skills')} for s in skills),
            key=lambda s: (s['group'], s['name']),
        ),
        'spells': sorted(
            ({'name': s['name'], 'mana': s.get('manaText') or ''} for s in spells),
            key=lambda s: s['name'],
        ),
        'damageTypes': ts_string_list(SRC / 'data/index.ts', 'DAMAGE_TYPES'),
        'gearSlots': [label for _, label in slots] + ['Weapon'],
        'items': items,
        'tiers': ['Bronze', 'Silver', 'Gold', 'Platinum', 'Legendary', 'Celestial'],
        'categories': ['Adventurer', 'Boss', 'Fan', 'Benefactor', 'Mystery', 'Quest', 'Floor'],
    }

    body = json.dumps(data, indent=1, ensure_ascii=False)
    header = '// Generated by tools/build_lootbox_data.py from the Crawler Sheets catalog. Do not edit.\n'
    OUT.mkdir(exist_ok=True)
    (OUT / 'Data.gs').write_text(f'{header}var LOOT_DATA = {body};\n')
    (OUT / 'data.js').write_text(f'{header}var LOOT_DATA = {body};\n')
    print(f"{len(data['skills'])} skills, {len(data['spells'])} spells, "
          f"{len(data['damageTypes'])} damage types, {len(data['gearSlots'])} slots, {len(data['items'])} items")


if __name__ == '__main__':
    main()
