"""One-line paraphrased summaries shown in the app. Keys are "<kind>:<id>".
Written fresh for the app (not copied from the books); see the page reference for full rules."""
SUMMARIES = {
    # Attack skills
    "skill:back-claw": "Animal rear-claw rake.",
    "skill:bite": "Animal bite; the target needs something you can clamp onto.",
    "skill:slice-attack": "Animal claw swipe; a starting attack for animal crawlers.",
    "skill:club": "Blunt one-handed bashing weapon.",
    "skill:improvised-weapons": "Hit someone with whatever you grab (1 lb up to your Str in lbs).",
    "skill:warhammer": "Heavy two-handed bashing weapon.",
    "skill:axe": "Chopping weapon.",
    "skill:dagger": "Light blade; later pierces armor and can be thrown.",
    "skill:longsword": "Classic blade.",
    "skill:rapier": "Finesse blade that uses Dex for damage and improves Evade.",
    "skill:foot-soldier": "Kicks and stomps; can pair with Powerful Strike or Smush.",
    "skill:noggin-nocker": "Headbutts; hurts you too until Rank 5. Pairs with Skullcracker or Powerful Strike.",
    "skill:pugilism": "Boxing; pairs with Dirty Fighting, Iron Punch or Powerful Strike.",
    "skill:unarmed-combat": "Everyone's basic punches and kicks; no Damage Effects.",
    "skill:wrasslin": "Grappling; a hit leaves the target Held. Pairs with Choke Out, Dirty Fighting or Toss.",
    "skill:choke-out": "Damage Effect: double total damage against a foe at 10% Health or less.",
    "skill:dirty-fighting": "Damage Effect: cheap shots that make the target Woozy.",
    "skill:iron-punch": "Damage Effect: extra base damage on punches.",
    "skill:powerful-strike": "Damage Effect: multiply the base dice result by this Skill's Rank.",
    "skill:skullcracker": "Damage Effect: extra base damage against a same-size foe.",
    "skill:smush": "Damage Effect: multiply total damage against a badly hurt foe.",
    "skill:toss": "Damage Effect: extra damage, ends Held, and throws a smaller foe.",
    "skill:bow": "Two-handed ranged weapon; needs arrows.",
    "skill:crossbow": "Mechanical ranged weapon; needs bolts.",
    "skill:handgun": "Pistol; needs ammo and adds no Stat to damage.",
    "skill:javelin": "Thrown spear.",
    "skill:shotgun": "Close-range spread firearm; needs shells.",
    "skill:shuriken": "Thrown stars.",
    "skill:slingshot": "Flings small stones; cheap ammo.",
    "skill:herding-weapons": "Shepherd's crook and similar herding tools (reach).",
    "skill:lance": "Reach weapon, best used when mounted.",
    "skill:polearm": "Two-handed reach weapon.",
    "skill:quarterstaff": "Two-handed reach staff that improves Evade.",
    "skill:creepy-chains": "Changbi Demon racial chain weapon: works like a Club with 10ft reach.",
    # Utility skills
    "skill:acute-ears": "Sharper hearing; more Mobs show on your minimap.",
    "skill:aiming": "On a ranged attack, take Disadvantage to add your Aiming Ranks and bonus damage.",
    "skill:alchemy": "Craft potions and poisons (crafting rules p.221).",
    "skill:ambush": "Int-Opposed. Get a surprise Action against approaching Mobs, attacking with Advantage.",
    "skill:animal-handling": "Int-Opposed. Calm or befriend an animal so it won't attack.",
    "skill:arcane": "Unopposed. Tell whether an item is magical.",
    "skill:attack-of-opportunity": "Interrupt attack when an adjacent foe moves away (not by Step).",
    "skill:backfire": "Compensated Anarchist only. Neutralize or take apart traps without a Sapper's Table.",
    "skill:balance": "Unopposed. Keep your footing on tricky or shifting surfaces.",
    "skill:basic-science": "Unopposed. Run 2-hour experiments to learn or confirm something.",
    "skill:bomb-surgeon": "Unopposed. Take bombs apart for parts or half-size bombs.",
    "skill:calligraphy": "Unopposed. Beautiful writing; needed to make scrolls from the Fourth Floor on.",
    "skill:cartography": "Unopposed. Work out where you are relative to other places.",
    "skill:cat-like-reflexes": "+10ft Move; use it in place of Dexterity Stat Checks.",
    "skill:catcher": "Interrupt: take a hit meant for an adjacent ally (can Step first). You can't Evade it.",
    "skill:cesta-punta": "Jai alai throwing with a xistera; Earth Hobby Potion only.",
    "skill:character-actor": "Each floor, borrow random abilities from a new Class.",
    "skill:chopper-pilot": "Unopposed. Stunts and chases on a motorcycle.",
    "skill:climbing": "Unopposed, rolled each minute. Make safe progress up a climb.",
    "skill:cockroach": "Unopposed. When an attack would drop you to 0%, drop to 10% instead.",
    "skill:cooking": "Unopposed. Turn ingredients into an edible meal for the party in 1 hour.",
    "skill:deception": "Int-Opposed. Lie convincingly (Disadvantage against Detect Lies).",
    "skill:detect-lies": "Cha-Opposed. Sense whether someone is lying.",
    "skill:detect-trap": "Unopposed. Spot a non-magic trap on a suspect object.",
    "skill:determine-value": "Sort your inventory by value.",
    "skill:diplomacy": "Int-Opposed. Get two opposing groups talking.",
    "skill:dodge": "+1 Evade Buff.",
    "skill:double-tap": "If your first attack is an Amazing Success, your second hit becomes a Critical Hit.",
    "skill:driving": "Unopposed. Racing, chasing and stunts in a vehicle.",
    "skill:dumpster-diving": "Unopposed, 1 hour per area. Scrounge useful junk.",
    "skill:endurance": "Unopposed. Keep going without becoming Fatigued (grinding, long marches).",
    "skill:engineering": "Unopposed. Build things with moving parts from Misc. Junk.",
    "skill:escape-artist": "Escape bonds (Unopposed) or being Held (Str-Opposed).",
    "skill:escape-plan": "Your HUD shows hidden doors and passages.",
    "skill:explosives-handling": "Unopposed. Handle standard explosives safely.",
    "skill:fabricate": "Unopposed. Make simple mundane items from Misc. Junk.",
    "skill:find-crawler": "Your HUD shows other crawlers within 1,000 feet.",
    "skill:find-trap": "Traps within 5 feet flash on your HUD just before they trigger.",
    "skill:first-aid": "Heal 1 Health Bar slot, plus 1 for each higher degree of Success.",
    "skill:gear-head": "Unopposed. Build high-performance engines (+5ft Move per Bonus Level).",
    "skill:goblin-explosives": "Unopposed. Use unstable goblin explosives; Crit Fails on a Natural 1–4.",
    "skill:good-first-impression": "Int-Opposed. A non-hostile NPC or Mob approaches with curiosity.",
    "skill:hide-in-shadows": "Int-Opposed. Hide while standing still; you become invisible to Mobs and HUDs.",
    "skill:improvised-explosive-device": "Unopposed. Build bombs and traps without a Sapper's Table.",
    "skill:incendiary-device-handling": "Unopposed. Handle incendiary devices safely.",
    "skill:infusion": "Put a potion's effect into a consumable item.",
    "skill:intimidate": "Cha-Opposed. Scare a foe so it becomes Staggered.",
    "skill:investigation": "Unopposed, 10 minutes. Learn something useful; also for Look for Clues.",
    "skill:iron-stomach": "Unopposed. Eat magic items (Amazing Success: +1 permanent Int).",
    "skill:jumping": "Unopposed. Running leap of up to Rank + Str feet.",
    "skill:leadership": "Int-Opposed. Coordinate parties so they get Advantage on their first attack against a Boss.",
    "skill:light-on-your-feet": "Unopposed. Running leap of Rank ×2 feet, reaching Dex ×2 feet high.",
    "skill:lockpicking": "Unopposed, takes Floor-number minutes. Pick a lock.",
    "skill:lore": "Unopposed. Know something about a neighborhood, its Mobs or its locals.",
    "skill:negotiation": "Int-Opposed, 5 minutes. Haggle prices with merchants.",
    "skill:pathfinder": "Your HUD map covers Rank × the normal area.",
    "skill:perception": "Unopposed. Notice details; also for Look for Clues.",
    "skill:performance": "Unopposed. Wow an audience in your specialty.",
    "skill:persuasion": "Int-Opposed, about 10 minutes. Convince someone to go along with you.",
    "skill:regeneration": "Heal 1 slot every round if Rank ≥ your Con, otherwise every other round.",
    "skill:religion": "Unopposed. Know the basics about a god and its followers.",
    "skill:repair": "Unopposed, 2 hours. Fix a broken item.",
    "skill:riding": "Stay on a panicking mount during action scenes.",
    "skill:ropework": "Unopposed. Knots, lassos and tying things up.",
    "skill:running": "Unopposed, each minute. Races and chases (+1 per 10ft Move).",
    "skill:salvage": "Unopposed, 1 hour. Recover half the materials from wrecked or failed crafts.",
    "skill:scutelliphily": "Unopposed. Identify patches and improve the patches you craft.",
    "skill:shield-block": "Interrupt: roll against each physical attack's to-hit to block it with a shield.",
    "skill:sleight-of-hand": "Int-Opposed. Move small objects without being noticed.",
    "skill:smithing": "Forge mundane metal items, weapons and armor.",
    "skill:stealth": "Int-Opposed. Move unseen; before combat, gain a free non-Attack Action.",
    "skill:streetwise": "Unopposed. Rumors, black markets and keeping a low profile in town.",
    "skill:survival": "Unopposed. Get through harsh, remote areas unharmed.",
    "skill:swimming": "Unopposed, every 30 seconds. Swim under pressure; causes Fatigue.",
    "skill:tactics": "Unopposed, once per combat. Party gets +1 or more to Attack, Damage or Evade.",
    "skill:tattoo-artistry": "Mundane tattoos (magical ones use crafting rules).",
    "skill:taunt": "Interrupt, Int-Opposed. Pull a Mob's attack onto yourself.",
    "skill:throwing": "Throw objects (Unopposed to hit an area, vs Evade to hit a foe); range Str ×10 ft.",
    "skill:tracking": "Unopposed. Find and follow tracks, re-rolling every 15 minutes.",
    "skill:trap-engineer": "Craft traps with a Sapper's Table and Trap Module.",
    "skill:zone-of-control": "Once per round, Interrupt-attack a foe entering an adjacent space (with Disadvantage).",
    # Spells
    "spell:air-buddy": "Launch yourself up to 10 × Int Mod away; cast twice to double jump.",
    "spell:astral-paw": "Spectral hand that manipulates things up to 30ft away.",
    "spell:bad-faith": "Necrotic attack on mind and soul.",
    "spell:bang-bro": "Your held weapon deals +2 Fire/Electric damage for a while.",
    "spell:clockwork-triplicate": "Split your pet or minion into three copies.",
    "spell:confusing-fog": "Fog that Mobs attack through with Disadvantage; your party sees through it.",
    "spell:dirt-clod": "Hurl a magic clod of dirt.",
    "spell:drain-life": "Necrotic tether that heals you at higher Ranks.",
    "spell:earworm": "Sonic attack by singing terribly.",
    "spell:fear": "Make a weak non-Boss Mob lose its Dex Mod, or run away.",
    "spell:fireball": "Slow fireball (attack with Disadvantage) with a 10ft Blast; still lands on a miss.",
    "spell:fire-fingers": "Melee flame touch.",
    "spell:frost-scar": "Melee ice touch.",
    "spell:grand-illusion": "Int-Opposed illusion that fools foes who see it.",
    "spell:heal": "Heal yourself 2 Health Bar slots (Interrupt). Everyone starts with it.",
    "spell:heal-critter": "Fully heal a pet or critter.",
    "spell:heal-others": "Heal a target 1d4 Health Bar slots (Interrupt).",
    "spell:heal-self": "Heal yourself 1d4 Health Bar slots (Interrupt).",
    "spell:hole": "Open a hole through a surface.",
    "spell:holy-aura": "Holy burst that damages only enemies around you.",
    "spell:hot-stuff-aura": "Shield slots (Cha Mod count, 2 each) for you and nearby allies.",
    "spell:ice-blast": "Compact blast of cold.",
    "spell:icicles": "Long-range ice projectiles.",
    "spell:intimate-touches": "Touch heal: the target heals slots equal to your Cha Mod.",
    "spell:lightning-bolt": "Bolt of lightning.",
    "spell:magic-missile": "Streak of pure force.",
    "spell:mind-tickle": "Psychic headache attack.",
    "spell:minion-army": "Turn some Mobs in an area into allies.",
    "spell:natures-breath": "Heal slots equal to a roll of this Spell's Rank damage die; works on pets.",
    "spell:oakhide": "+2 Damage Resistance while it lasts.",
    "spell:paladins-smite": "Holy strike of divine wrath.",
    "spell:panty-dropper": "Int-Opposed charm; a non-Boss target stops fighting.",
    "spell:ping": "Reveal the location of nearby non-crawlers and Mobs.",
    "spell:protective-shell": "Force dome that keeps Mobs out; doesn't stop magic.",
    "spell:puddle-jumper": "Teleport yourself and up to 3 party members.",
    "spell:rise-dead-minion": "A skeleton pops up and attacks for 1d8 + Int Necrotic.",
    "spell:rootfoot": "Roots leave a Medium-or-smaller victim Held.",
    "spell:second-chance": "Raise a lower-level Mob as a temporary undead minion.",
    "spell:shield": "Force field with 2 slots (Con Mod each) that absorbs non-magic damage first.",
    "spell:shock-treatment": "Electric finger-lightning.",
    "spell:solsplash": "Fire sunbeam that also hits those around the target.",
    "spell:soul-collector": "Necrotic spirit siphon.",
    "spell:thunderlash": "Sonic whip.",
    "spell:torch": "Floating light orb (20ft bright + 20ft dim).",
    "spell:tripper": "Set off every movement, heat and weight trap nearby.",
    "spell:turn-undead": "Cha-Opposed; undead in the area flee.",
    "spell:twinkle-toes": "Double a pet's or minion's Move.",
    "spell:unnecessary-force": "Force shockwave.",
    "spell:vine-porn": "Piercing vines tear at the target.",
    "spell:wall-of-fire": "Create a 30ft wall of fire.",
    "spell:water-breathing": "The target breathes underwater.",
    "spell:web": "Cone of webbing that leaves everyone it hits Held.",
    "spell:wilburs-slow-build-fireblast": "Hold a fire ring on your finger and unleash it with your next attack.",
    "spell:wisp-armor": "Cut magic damage to Rank 1 base damage; immune to Mind Control.",
}
